#!/bin/bash

java_executable="java"

java_program="src/tracer/RayTracer.java"

input_directory="assets"

for input_file in "$input_directory"/*.txt; do
    if [ -f "$input_file" ]; then
        filename=$(basename "$input_file" .txt)

        echo "Running $java_program with input file: $input_file"
        $java_executable -cp . "$java_program" "$input_file"

        echo "Done processing $filename"
    fi
done

echo "Script completed"

